### ISSUE TITLE
applyIJ_parallel function used but never defined

### ISSUE THREAD

**Issue by roshankern** [cheeseman-lab/OpticalPooledScreens#2]
The `applyIJ_parallel` function is used for 2 processes in `ops/firesnake.py` but is never defined. It looks like this function should be present in utils (`ops.utils.applyIJ_parallel`) but it is not. The non-parallel version of this function (`applyIJ`) is present.

**Comment by mat10d** [comment]
Will address once you re-merge. Good spot
