### ISSUE TITLE
QC Split From Rest Of Pipeline

### ISSUE THREAD

**Issue by roshankern** [cheeseman-lab/OpticalPooledScreens#6]
The current example analysis has the processing steps of OPS separate from the evaluation steps. For example, in [sbs_1](https://github.com/cheeseman-lab/OpticalPooledScreens/tree/main/example_analysis/sbs_1) a `sbs_1.smk` file is used to call the alignment, segmentation, and other processing steps while the QC steps are called in `sbs_1_eval.py`.

Long term, I think it makes more sense to call the QC functions in the same snakemake process. This would make more code reusable and make deriving QC stats an optional extension of the processing pipeline.

Open to your thoughts on this @mat10d

**Comment by mat10d** [comment]
We should do that. It may be a bit tricky in snakemake with inputs and outputs, though. If you want to see how to set this up when you run the snakemake files, that would be a plus

**Comment by roshankern** [comment]
After looking more into snakemake and our current codebase, I definitely think it would be beneficial to include QC as part of the snakemake pipeline instead of a separate python module that gets called in scripts.

However, I would prefer to keep the current QC setup we refactor the examples. I think after we refactor the examples and I become more familiar with the entire pipeline we will be able to make better decisions on how to include QC and all other code in one coherent tool.

So in #7 I opt to call the QC code in the same way as the old examples.

**Comment by mat10d** [comment]
Ok, good approach for now. We will find a way to integrate it into the snakemake at a later time point
